# Generated by Django 6.0.4 on 2026-06-05 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('numeroPrenda', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePrenda', models.CharField(max_length=100)),
                ('descripcionPrenda', models.TextField(max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('precioNetoUnitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PrendaMomentanea',
            fields=[
                ('numeroPrenda', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePrenda', models.CharField(max_length=100)),
                ('descripcionPrenda', models.TextField(max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('precioNetoUnitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
