# Generated by Django 6.0.4 on 2026-05-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compra',
            new_name='Inventario',
        ),
    ]
