# Generated by Django 6.0.4 on 2026-05-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_compra_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='codigoPrenda',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nombrePrenda',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='precioNetoUnitario',
            field=models.CharField(max_length=200),
        ),
    ]
