# Generated by Django 6.0.4 on 2026-06-13 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_informacionusuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionusuario',
            name='salario',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
