# Generated by Django 6.0.4 on 2026-05-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroVenta', models.TextField(max_length=200)),
                ('fechaVenta', models.DateTimeField(auto_now_add=True)),
                ('codigoPrenda', models.TextField(max_length=200)),
                ('nombrePrenda', models.TextField(max_length=200)),
                ('descripcionPrenda', models.TextField(max_length=200)),
                ('cantidadComprada', models.TextField(max_length=200)),
                ('precioNetoUnitario', models.TextField(max_length=200)),
                ('precioNetoTotal', models.TextField(max_length=200)),
                ('iva', models.TextField(max_length=200)),
                ('precioBrutoTotal', models.TextField(max_length=200)),
                ('medioDePago', models.TextField(max_length=200)),
            ],
        ),
    ]
