# Generated by Django 6.0.4 on 2026-05-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='cantidadComprada',
            new_name='cantidadVendida',
        ),
    ]
