# Generated by Django 6.0.4 on 2026-06-13 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_iva_alter_venta_numeroventa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='cantidadVendida',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
