# Generated by Django 6.0.4 on 2026-05-13 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_cantidadcomprada_venta_cantidadvendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidadVendida',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='codigoPrenda',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fechaVenta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='iva',
            field=models.CharField(default=19, max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='medioDePago',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombrePrenda',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numeroVenta',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precioBrutoTotal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precioNetoTotal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precioNetoUnitario',
            field=models.CharField(max_length=200),
        ),
    ]
