# Generated by Django 6.0.4 on 2026-06-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_ventadetalle_cantidadvendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numeroVenta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ventamomentanea',
            name='numeroVenta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
