# Generated by Django 6.0.4 on 2026-05-31 19:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('numeroCompra', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaCompra', models.DateTimeField(default=django.utils.timezone.now)),
                ('iva', models.IntegerField(default=19)),
                ('precioBrutoTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medioDePago', models.CharField(max_length=30)),
                ('nombreProveedor', models.CharField(max_length=100)),
                ('direccionProveedor', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('nombrePrenda', models.CharField(max_length=100)),
                ('descripcionPrenda', models.TextField(max_length=200)),
                ('cantidadComprada', models.IntegerField(default=0)),
                ('precioNetoUnitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precioNetoTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pk', models.CompositePrimaryKey('numeroCompra', 'numeroPrenda', blank=True, editable=False, primary_key=True, serialize=False)),
                ('numeroCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
                ('numeroPrenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prenda')),
            ],
        ),
        migrations.CreateModel(
            name='CompraMomentanea',
            fields=[
                ('numeroCompra', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaCompra', models.DateTimeField(default=django.utils.timezone.now)),
                ('iva', models.IntegerField(default=19)),
                ('precioBrutoTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medioDePago', models.CharField(max_length=30)),
                ('nombreProveedor', models.CharField(max_length=100)),
                ('direccionProveedor', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalleMomentanea',
            fields=[
                ('nombrePrenda', models.CharField(max_length=100)),
                ('descripcionPrenda', models.TextField(max_length=200)),
                ('cantidadComprada', models.IntegerField(default=0)),
                ('precioNetoUnitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precioNetoTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pk', models.CompositePrimaryKey('numeroCompra', 'numeroPrenda', blank=True, editable=False, primary_key=True, serialize=False)),
                ('numeroPrenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prenda')),
                ('numeroCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compramomentanea')),
            ],
        ),
    ]
