# Generated by Django 6.0.4 on 2026-05-13 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidadComprada',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='codigoPrenda',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='direccionProveedor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='compra',
            name='iva',
            field=models.CharField(default=19, max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='medioDePago',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nombrePrenda',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nombreProveedor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numeroCompra',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precioBrutoTotal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precioNetoTotal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precioNetoUnitario',
            field=models.CharField(max_length=200),
        ),
    ]
