# Generated by Django 6.0.4 on 2026-06-13 05:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='iva',
            field=models.IntegerField(default=19, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numeroCompra',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precioBrutoTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='cantidadComprada',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='numeroCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='numeroPrenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prenda', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='precioNetoTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='precioNetoUnitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
