# Generated by Django 6.0.4 on 2026-06-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0002_prendamomentanea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetallemomentanea',
            name='numeroPrenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prendamomentanea'),
        ),
    ]
