# Generated by Django 6.0.4 on 2026-06-13 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_iva_alter_compra_numerocompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='cantidadComprada',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
