# Generated by Django 6.0.4 on 2026-06-15 02:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compradetalle_cantidadcomprada'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numeroCompra',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compradetallemomentanea',
            name='cantidadComprada',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='compradetallemomentanea',
            name='numeroCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compramomentanea', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='compradetallemomentanea',
            name='numeroPrenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prendamomentanea', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='compradetallemomentanea',
            name='precioNetoTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='compradetallemomentanea',
            name='precioNetoUnitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='compramomentanea',
            name='iva',
            field=models.IntegerField(default=19, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='compramomentanea',
            name='numeroCompra',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compramomentanea',
            name='precioBrutoTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
